### ISSUE TITLE
Creating a new token doesn't invalidate already issued token

### ISSUE THREAD

**Issue by SidShaytay** [hylander0/MasterKeyAuthentication#1] opened 2014-08-13 00:18 UTC
How does one invalidate or expire the tokens? For example, in the case below, shouldn't token1 be invalidated when token2 is issued?

Working at present:
1. User authenticates with username,password, receives token1
1. User authenticates with username,password, receives token2
1. Both token1 and token2 are active

**Comment by hylander0** [comment] 2014-08-13 14:22
This is by design.  Tokens will be valid until the expiration time has passed.  Generating a new one is the same as the old one expect it is generated against a different expiration date/time.  

If you want to invalidate all past submitted tokens you will need to implement this: http://stackoverflow.com/a/19505060/2554459

I haven't tried this so I can't vouch for this.

**Comment by hylander0** [comment] 2015-04-03 19:55
Closing issue since it invalidation works as expected.

**Closed as completed by hylander0** 2015-04-03 19:55 UTC
